name: build and test
on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install node 14.x
        uses: actions/setup-node@v2
        with:
          node_version: 14.x
      - name: Install dependencies
        run: npm clean-install
      - name: Run the application
        run: nohup npm run start &
      - name: Run HawkScan
        uses: stackhawk/hawkscan-action@v1.3.1
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}
